<a href="https://colab.research.google.com/github/PeedroPrado/3-DSM/blob/main/ex10_pdf04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercício 10 – Verificação computacional com NumPy (opcional)

a)
Calcular autovalores e autovetores de
b) Construir 𝑃 e 𝐷 a partir da saída do NumPy.
c)
Verificar numericamente que 𝐴 ≈ 𝑃𝐷𝑃−1.

A =[ 4 1
     1 4 ]

In [ ]:
import numpy as np
A = np.array([[4, 1],
[1, 4]])
# 1. Autovalores e autovetores
vals, vecs = np.linalg.eig(A)
print("Autovalores:", vals)
print("Autovetores (colunas de P):")
print(vecs)
# 2. Montando P e D
P = vecs
D = np.diag(vals)
# 3. Reconstrução de A
A_rec = P @ D @ np.linalg.inv(P)
print("A reconstruída:")
print(A_rec)
# Verificação
print("Diferença A - A_rec:")
print(A - A_rec)

Autovalores: [5. 3.]
Autovetores (colunas de P):
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
A reconstruída:
[[4. 1.]
 [1. 4.]]
Diferença A - A_rec:
[[0. 0.]
 [0. 0.]]
